### ISSUE TITLE
Running - Error : CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by nicolasp9-dev** [tbennun/cudnn-training#17]
Hi,

When I run your code on my computer I have the following error : 
```
CUDNN failure: CUDNN_STATUS_BAD_PARAM
/home/admin/cudnn-training-master/lenet.cu:658
Aborting...
```

It correspond to a problem with : cudnnConvolutionBackwardFilter() function.
After verification of parameters following the cudNN documentation I was not able to find the problem.

Adress sent as parameters : 
```
Cudnn handle : 0x627eb60
Alpha : 0x7ffe073b5ce0
pool1Tensor : 0x122d6790
Pool1 : 0xb05c20000
conv2Tensor : 0x122d67f0
dpool2 : 0xb06540000
conv2Desc : 0x122d6ab0
conv2bwalgo : 2
workspace : 0xb06840000
m_workspaceSize : 11141120
Beta : 0x7ffe073b5cf0
conv2filterDesc : 0x122d6a10
gconv2 : 0xb058fa000
```
so, no NULL values

And it seems that every other mentioned issues mentioned in the documentation do not concern your program.

Do you have an idea how to solve this problem ?

Thanks,

Nicolas

**Comment by tbennun** [comment]
I suspect that the issue is a result of tensor dimensionality problems. Are you using the original setup? 
What are the sizes of the tensors in the parameters?

**Comment by nicolasp9-dev** [comment]
Hi, 
Thank a lot for your answer,

The only thing I did is to change the function name at line 438 from
```
 checkCUDNN(cudnnSetConvolution2dDescriptor(convDesc,
                                                   0, 0,
                                                   1, 1,
                                                   1, 1,
                                                   CUDNN_CROSS_CORRELATION));
```
to 
 ```
checkCUDNN(cudnnSetConvolution2dDescriptor_v4(convDesc,
                                                   0, 0,
                                                   1, 1,
                                                   1, 1,
                                                   CUDNN_CROSS_CORRELATION));
```
Because I'm using cudNN v6.

Here are the informations about tensors :
pool1Tensor : n : 64 c : 20 h : 12 w : 12 nStride : 2880 cStride : 144 hStride : 12 wstride : 1
Conv2Tensor : n : 64 c : 50 h : 8 w : 8 nStride : 3200 cStride : 64 hStride : 8 wstride : 1

It you need more informations, just tell me.

Thanks a lot,

Nicolas

**Comment by tbennun** [comment]
CUDNN v6 was not tested with the sample. Have you tried running the application with CUDNN v5?

**Comment by tbennun** [comment]
Please try the code now, after PR #23 has been merged. Have you performed any other modifications to the code? (sizes, data, etc.)

**Comment by nicolasp9-dev** [comment]
Hi, 

Sorry I just saw your two lasts messages, I tried this new version of the code and it works perfectly well. (Using a cudnnSetConvolution2dDescriptor_v4 with CUDnn v5 was not a good idea)

Thanks a lot for your support ! 

Nicolas
