### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Da-Ki-Ko** [tbennun/cudnn-training#8]
I have the same runtime error as in issue #3. There the error is not discussed in detail and the proposed fix is to set the batch size in the test stage to **64**.
In my opinion the correct batch size in the test stage should be **1** because we are classifying just one image. 
Can you give me some advice? I am not sure whether I am doing something wrong or if there is a bug in the library. 
Here are some more details about the problem.

**Environment Description**
I am using Visual Studio 2013 community edition on Win7 64. I have graphical card GeForce GTX 960.

**Problem Details**
I can compile the code successfully. 
However when I run the example there is a run time error CUDNN_STATUS_EXECUTION_FAILED during the call  `test_context.ForwardPropagation()` at line #982.

After examination of the code I found the following behavior. 
It has to do with the "batch size" parameter of the constructor calls at lines:

```
#783 // Initialize CUDNN/CUBLAS training context
#784 TrainingContext context(...)

```

and 

```
#968// Initialize a TrainingContext structure for testing (different batch size)
#969 TrainingContext test_context(...). 

```

The values of the "batch size" parameter  are set to **64** and **1** during training and testing respectively.
I examined the code further and found out that when the batch size is 64 the  parameter 
m_workspaceSize in srtucture TrainingContext is **3464.** When batch size is 1 the m_workspaceSize is **19508.**
I experimented with two other settings of the batch sizes. In both cases the program runs without error:
- **64** and **2.** In both cases the m_workspaceSize value is the same **3464.**
- **1** and **1.** In both cases the m_workspaceSize value is the same **19508.**

Thank you in advance.

**Comment by madhurgoel** [comment]
I faced the same problem(CUDNN failure: CUDNN_STATUS_EXECUTION_FAILED) on Ubuntu 14.04, using cuda 7.5 with CUDNN 5.0 on GTX 980 TI. Also 
1) please add $ENV{CUDNN_PATH}/lib64 to link_directories in CMakeLists.txt
2) The default name of test mnist files as provided in some of the archive files(mnist.tar.gz) is in the format "train-labels-idx1-ubyte" and you expect a file "train-labels.idx1-ubyte" (see the '.' instead of '-' after labels)

**Comment by tbennun** [comment]
@Da-Ki-Ko I'll look into the issue when possible.

@madhurgoel, if you can upload a pull request for both of your changes, I'll gladly merge them.

> The default name of test mnist files as provided in some of the archive files(mnist.tar.gz) is in the format "train-labels-idx1-ubyte" and you expect a file "train-labels.idx1-ubyte" (see the '.' instead of '-' after labels)

That is correct, the invalid naming convention was due to Windows' handling of a gzipped filename.

**Comment by madhurgoel** [comment]
In my case I just renamed my own dataset files, but for pull request if I would change it in the code then it might not work on windows machine. I do not have windows machine to test it. And regarding first change my push failed with error remote: Permission to tbennun/cudnn-training.git denied to madhurgoel.
although here is the content of pull request

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 94ff195..5757297 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,7 +23,7 @@ if(USE_GFLAGS)
 endif()

 include_directories($ENV{CUDNN_PATH} $ENV{CUDNN_PATH}/include)
-link_directories($ENV{CUDNN_PATH} $ENV{CUDNN_PATH}/lib)
+link_directories($ENV{CUDNN_PATH} $ENV{CUDNN_PATH}/lib $ENV{CUDNN_PATH}/lib64)

 cuda_add_executable(trainlenet lenet.cu readubyte.cpp)
 cuda_add_cublas_to_target(trainlenet)

**Comment by tbennun** [comment]
According to how Github works, you first have to fork the project, then commit and push. After doing so, it will ask you on the website if you want to open a pull request.

**Comment by Da-Ki-Ko** [comment]
I found a solution to the problem.
It seams that the test phase uses the workspace allocated in the GPU during the training phase. In my environment this results in an error because the test workspace is larger than the training workspace.
I solved the problem by resizing the allocated workspace in the GPU if necessary. To do that I added the following code at line #970 in lenet.cu:

```
if (context.m_workspaceSize < test_context.m_workspaceSize)
{
    checkCudaErrors(cudaFree(d_cudnn_workspace));
    checkCudaErrors(cudaMalloc(&d_cudnn_workspace, test_context.m_workspaceSize));
}
```

**Comment by tbennun** [comment]
Indeed this sounds like a reasonable solution. Can you create a pull request for this?

**Comment by tbennun** [comment]
Merged. I'm keeping the issue open for the other pull request I'm waiting for, from @madhurgoel 

Thanks!

**Comment by tbennun** [comment]
Thank you both for your help. Closing the issue.
